/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    ElementalEmission: (() => {
      const name = "ElementalEmission";
      return defineComponent(
        world,
        {
          daily_emission: RecsType.BigInt,
        },
        {
          metadata: {
            name: name,
            types: ["u128"],
          },
        }
      );
    })(),
    ElementalDispersion: (() => {
      const name = "ElementalDispersion";
      return defineComponent(
        world,
        {
          ARPS: RecsType.BigInt,
          lastUpdateTimestamp: RecsType.Number,
        },
        {
          metadata: {
            name: name,
            types: ["u128","u64"],
          },
        }
      );
    })(),
    ElementalAccretion: (() => {
      const name = "ElementalAccretion";
      return defineComponent(
        world,
        {
          total_accretion: RecsType.BigInt,
        },
        {
          metadata: {
            name: name,
            types: ["u128"],
          },
        }
      );
    })(),
    Mass: (() => {
      const name = "Mass";
      return defineComponent(
        world,
        {
          mass: RecsType.BigInt,
        },
        {
          metadata: {
            name: name,
            types: ["u128"],
          },
        }
      );
    })(),
    Orbit: (() => {
      const name = "Orbit";
      return defineComponent(
        world,
        {
          parent_id: RecsType.BigInt,
        },
        {
          metadata: {
            name: name,
            types: ["u128"],
          },
        }
      );
    })(),
    OrbitMass: (() => {
      const name = "OrbitMass";
      return defineComponent(
        world,
        {
          mass: RecsType.BigInt,
        },
        {
          metadata: {
            name: name,
            types: ["u128"],
          },
        }
      );
    })(),
    Owner: (() => {
      const name = "Owner";
      return defineComponent(
        world,
        {
          owner: RecsType.BigInt,
        },
        {
          metadata: {
            name: name,
            types: ["ContractAddress"],
          },
        }
      );
    })(),
  };
}
